// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mathApp.Models;

#nullable disable

namespace mathApp.Migrations
{
    [DbContext(typeof(MySQLDBContext))]
    [Migration("20240215141533_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UsuarioHasLicao", b =>
                {
                    b.Property<int>("LicoesidLicao")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosidUsuario")
                        .HasColumnType("int");

                    b.HasKey("LicoesidLicao", "UsuariosidUsuario");

                    b.HasIndex("UsuariosidUsuario");

                    b.ToTable("UsuarioHasLicao");
                });

            modelBuilder.Entity("mathApp.Models.Licao", b =>
                {
                    b.Property<int>("idLicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("conteudo")
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("recompensa")
                        .HasColumnType("int");

                    b.HasKey("idLicao");

                    b.ToTable("Licoes");
                });

            modelBuilder.Entity("mathApp.Models.Usuario", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("XP")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("idUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("UsuarioHasLicao", b =>
                {
                    b.HasOne("mathApp.Models.Licao", null)
                        .WithMany()
                        .HasForeignKey("LicoesidLicao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mathApp.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosidUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
