// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mathApp.Models;

#nullable disable

namespace mathApp.Migrations
{
    [DbContext(typeof(MySQLDBContext))]
    partial class MySQLDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("mathApp.Models.Atividade", b =>
                {
                    b.Property<int>("idAtividade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("conteudo")
                        .HasColumnType("longtext");

                    b.Property<string>("enunciado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("idLicao")
                        .HasColumnType("int");

                    b.Property<bool?>("isFinished")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("solucao")
                        .HasColumnType("longtext");

                    b.HasKey("idAtividade");

                    b.HasIndex("idLicao");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("mathApp.Models.Licao", b =>
                {
                    b.Property<int>("idLicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("conteudo")
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("recompensa")
                        .HasColumnType("int");

                    b.HasKey("idLicao");

                    b.ToTable("Licoes");
                });

            modelBuilder.Entity("mathApp.Models.Usuario", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("XP")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("idUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("mathApp.Models.UsuarioHasLicao", b =>
                {
                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<int>("idLicao")
                        .HasColumnType("int");

                    b.Property<int?>("LicaoidLicao")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioidUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("isFinished")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("idUsuario", "idLicao");

                    b.HasIndex("LicaoidLicao");

                    b.HasIndex("UsuarioidUsuario");

                    b.ToTable("Matriculas");
                });

            modelBuilder.Entity("mathApp.Models.Atividade", b =>
                {
                    b.HasOne("mathApp.Models.Licao", "Licao")
                        .WithMany("Atividades")
                        .HasForeignKey("idLicao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Licao");
                });

            modelBuilder.Entity("mathApp.Models.UsuarioHasLicao", b =>
                {
                    b.HasOne("mathApp.Models.Licao", "Licao")
                        .WithMany("Matriculas")
                        .HasForeignKey("LicaoidLicao");

                    b.HasOne("mathApp.Models.Usuario", "Usuario")
                        .WithMany("Matriculas")
                        .HasForeignKey("UsuarioidUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Licao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("mathApp.Models.Licao", b =>
                {
                    b.Navigation("Atividades");

                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("mathApp.Models.Usuario", b =>
                {
                    b.Navigation("Matriculas");
                });
#pragma warning restore 612, 618
        }
    }
}
